apiVersion: v1
kind: Pod
metadata:
  name: label-pod
  labels:
    environment: staging
    release: alpha1.1
    tier: kaleyra
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80